[package]
name = "aldoc"
version = "0.1.0"
authors = ["sinono3 <aldoacevedo1993@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
nom = "5"
clap = "3.0.0-beta.1"
